name: Quality

on: [push]

jobs:
  golangci:
    name: GolangCI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GolangCI
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
